version: '3.2'
services:
  pureftpd:
    restart: always
    build:
       context: .
       dockerfile: "./Dockerfile.pureftpd"
    ports:
      - "21:21"
      - "20:20"
      - "40000-40050:40000-40050"
    volumes:
       - ./pure-ftpd:/etc/pure-ftpd
       - ./ftp_home:/ftp_home
       
